# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conv1xk": "00_model.ipynb",
         "init_cnn_1d": "00_model.ipynb",
         "splitter": "00_model.ipynb",
         "ResidualBlock": "00_model.ipynb",
         "ResNetAudio": "00_model.ipynb",
         "replace_head": "00_model.ipynb",
         "resnet1d18": "00_model.ipynb",
         "resnet1d34": "00_model.ipynb",
         "AudioBlock": "01_data.ipynb",
         "TensorAudio": "01_data.ipynb",
         "AudioFixLength": "01_data.ipynb",
         "AudioResample": "01_data.ipynb",
         "AudioToMono": "01_data.ipynb",
         "AudioRandomCrop": "01_data.ipynb",
         "AudioAddNoise": "01_data.ipynb",
         "AudioToTensor": "01_data.ipynb"}

modules = ["model.py",
           "data.py"]

doc_url = "https://floleuerer.github.io/fastai2_resnet_audio/"

git_url = "https://github.com/floleuerer/fastai2_resnet_audio/tree/master/"

def custom_doc_links(name): return None
