# AUTOGENERATED! DO NOT EDIT! File to edit: 09_tutorial.ipynb (unless otherwise specified).

__all__ = ['path', 'length', 'device', 'dblocks', 'dls', 'config', 'model', 'learn']

# Cell
from .model import *
from .data import *
from fastai2.vision.all import *

# Cell
path = untar_data('https://storage.googleapis.com/ml-animal-sounds-datasets/macaques_24414Hz.zip')

# Cell

length = 0.5
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
dblocks = DataBlock(blocks = (AudioBlock,CategoryBlock),
                 get_items=get_files,
                 splitter=RandomSplitter(seed=42),
                 get_y=parent_label,
                 item_tfms=[AudioRandomCrop(length=length),
                            AudioFixLength(length=length),
                           ],
                 batch_tfms=[AudioAddNoise(device=device)]
                 )

dls=dblocks.dataloaders(path, bs=128)

# Cell
config = resnet1d18
config['num_classes'] = 8

# Cell
model = ResNetAudio(**config)

# Cell
learn = Learner(dls, model, metrics=accuracy, cbs=ShowGraphCallback())

# Cell
learn.unfreeze()
learn.fit_one_cycle(5, 1e-3)